name: Run Spring Batch Job

on:
  workflow_dispatch:
    inputs:
      batch_job:
        description: "생일 d-7 잡 실행"
        required: true
        default: "BirthdayRemindJob"
  schedule:
    - cron: "0 2 * * *"

jobs:
  run-batch-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create application.yml
        working-directory: ./
        run: |
            mkdir -p src/main/resources
            touch src/main/resources/application.yml
            echo "${{ secrets.APP_SECRET_KEY }}" >> src/main/resources/application.yml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Check built files
        run: ls -lh build/libs/

      - name: Run Spring Batch Job - 1 Week
        env:
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        run: java -jar build/libs/makeawish-batch-server-0.0.1-SNAPSHOT.jar --spring.batch.job.name=BirthdayRemindJob -dateDiff=7 -templateName=WISH_REMIND_WEEK_BEFORE

      - name: Run Spring Batch Job - 1 Day
        env:
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        run: java -jar build/libs/makeawish-batch-server-0.0.1-SNAPSHOT.jar --spring.batch.job.name=BirthdayRemindJob -dateDiff=1 -templateName=WISH_REMIND_DAY_BEFORE

